import { Inject, Injectable, Logger } from "@nestjs/common";
import { CommandBus, CommandHandler, EventBus } from "@nestjs/cqrs";

import { BaseCommandHandler, type HandleResult } from "../../../../infra/cqrs/base-command.handler";
import {
  CREDIT_STATEMENT_REPOSITORY,
  type CreditStatementRepositoryPort,
} from "../../domain/ports/credit-statement.repository.port";
import { GenerateScheduledStatementsCommand } from "./generate-scheduled-statements.command";
import { GenerateStatementsCommand } from "./generate-statements.command";

/**
 * Generates the statements whose scheduled close has arrived, each through the same
 * `GenerateStatementsCommand` a user triggers from "Generar facturación". One account
 * failing (say its dates now overlap a close generated by hand) never stops the rest:
 * it is logged and left for the user, who sees it still open.
 */
@Injectable()
@CommandHandler(GenerateScheduledStatementsCommand)
export class GenerateScheduledStatementsHandler extends BaseCommandHandler<
  GenerateScheduledStatementsCommand,
  number,
  null
> {
  private readonly logger = new Logger(GenerateScheduledStatementsHandler.name);

  constructor(
    eventBus: EventBus,
    private readonly commandBus: CommandBus,
    @Inject(CREDIT_STATEMENT_REPOSITORY)
    private readonly statements: CreditStatementRepositoryPort,
  ) {
    super(eventBus);
  }

  protected async loadContext(): Promise<null> {
    return null;
  }

  protected async handle(
    command: GenerateScheduledStatementsCommand,
  ): Promise<HandleResult<number>> {
    const due = await this.statements.listDueScheduled(command.now);
    let generated = 0;
    for (const d of due) {
      try {
        await this.commandBus.execute(
          new GenerateStatementsCommand(
            d.userId,
            d.accountId,
            d.periodStart,
            d.closedAt,
            d.dueDate,
          ),
        );
        generated++;
      } catch (error) {
        this.logger.warn(
          `Scheduled statement of account ${d.accountId} not generated: ${(error as Error).message}`,
        );
      }
    }
    return { result: generated, events: [] };
  }
}
