import { Module } from "@nestjs/common";
import { CqrsModule } from "@nestjs/cqrs";
import { ScheduleModule } from "@nestjs/schedule";

import { ExchangeRateModule } from "../../domains/exchange-rate/exchange-rate.module";
import { IdempotencyRecordModule } from "../../domains/idempotency-record/idempotency-record.module";
import { IpGeolocationCacheModule } from "../../domains/ip-geolocation-cache/ip-geolocation-cache.module";
import { UserModule } from "../../domains/user/user.module";
import { ExchangeRateCron } from "./exchange-rate.cron";
import { IdempotencyCleanupCron } from "./idempotency-cleanup.cron";
import { IpGeolocationCachePurgeCron } from "./ip-geolocation-cache-purge.cron";
import { SessionCleanupCron } from "./session-cleanup.cron";
import { StatementGenerationCron } from "./statement-generation.cron";

/**
 * Cross-cutting home for every scheduled automation this app runs — same tier as
 * `infra/prisma`/`infra/auth`/`infra/http`. `ScheduleModule.forRoot()` wires
 * `@nestjs/schedule` once; each `*.cron.ts` file is a thin trigger that dispatches
 * a command via `CommandBus` into the relevant domain's own handler (no business
 * logic lives here). `CqrsModule` is imported directly (a static class reference,
 * not a dynamic `forRoot()` module) so it resolves to the SAME singleton instance
 * the domain modules already register, sharing one `CommandBus`. (Statements are
 * no longer generated by a cron: the user generates each one with the dates from
 * the bank's statement — see `docs/PENDING.md` — except when its close was SCHEDULED
 * with "Editar fechas" on the open period: `StatementGenerationCron` then generates it
 * when that close arrives.)
 */
@Module({
  imports: [
    ScheduleModule.forRoot(),
    CqrsModule,
    ExchangeRateModule,
    IdempotencyRecordModule,
    IpGeolocationCacheModule,
    UserModule,
  ],
  providers: [
    ExchangeRateCron,
    IdempotencyCleanupCron,
    IpGeolocationCachePurgeCron,
    SessionCleanupCron,
    StatementGenerationCron,
  ],
})
export class CronModule {}
